lms/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include, re_path
from students.views import hello, get_students, update_student, IndexPage

urlpatterns = [
    path("", IndexPage.as_view(), name="index"),
    # path("index/", index),
    path("admin/", admin.site.urls),
    path("hello/", hello),
    path("students/", include("students.urls")),
    path('oauth/', include('social_django.urls'), name='social')
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path("__debug__/", include(debug_toolbar.urls)),
                  ] + urlpatterns

students/urls.py
from django.urls import path
from students.views import (
    hello,
    get_students,
    # create_student,
    update_student,
    delete_student,
    create_teacher,
    test_view,
    search_view, CreateStudent, UpdateStudent, LoginStudent,
    RegistrationStudent, LogoutStudent, send_email, ActivateUser
)

app_name = "students"

urlpatterns = [
    path("", get_students, name="list"),
    path("create/", CreateStudent.as_view(), name="create"),
    path("update/<int:pik>/", UpdateStudent.as_view(), name="update"),
    path("create-teacher/", create_teacher, name="create-teacher"),
    path("delete/<int:pk>/", delete_student, name="delete"),
    path("test/", test_view, name="test"),
    path("search/", search_view, name="search"),
    path("login/", LoginStudent.as_view(), name="login"),
    path("logout/", LogoutStudent.as_view(), name="logout"),
    path("registration/", RegistrationStudent.as_view(), name="registration"),
    path('send_email/', send_email, name='send_email'),
    path('activate/<str:uidb64>/<str:token>', ActivateUser.as_view(),
         name='activate')
]

students/models.py
import datetime

import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, User
from django.core.mail import send_mail
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models
from django.db.models.signals import post_save, pre_save, post_delete, \
    post_init, post_migrate, pre_delete
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField

from faker import Faker

from students.managers import PeopleManager
from students.validators import no_elon_validator

from django.utils.translation import ugettext as _
from students.managers import CustomUserManager
from django.contrib.auth import get_user_model


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    photo = models.ImageField(upload_to='user_photos/', null=True, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )

    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class ExtendedUser(CustomUser):
    people = PeopleManager()

    class Meta:
        proxy = True
        ordering = ('first_name',)

    def some_action(self):
        print(self.username)


class Person(models.Model):
    first_name = models.CharField(
        max_length=60, null=False, validators=[MinLengthValidator(2)]
    )
    last_name = models.CharField(
        max_length=80, null=False, validators=[MinLengthValidator(2)]
    )
    email = models.EmailField(max_length=120, null=True,
                              validators=[no_elon_validator])

    phone_number = PhoneNumberField(
        unique=True,
        null=True,
    )

    class Meta:
        abstract = True


class Student(Person):
    birthdate = models.DateField(null=True, default=datetime.date.today)

    course = models.ForeignKey(
        "students.Course", null=True, related_name="students",
        on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = "My student"
        verbose_name_plural = "All students"
        ordering = ['birthdate']

    def __str__(self):
        return f"{self.full_name()}, {self.age()}, {self.email} ({self.id})"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def age(self):
        return datetime.datetime.now().year - self.birthdate.year

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            st = cls(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birthdate=faker.date_time_between(start_date="-30y",
                                                  end_date="-18y"),
            )
            st.save()


class Course(models.Model):
    id = models.UUIDField(
        primary_key=True, unique=True, default=uuid.uuid4, editable=False
    )
    name = models.CharField(null=False, max_length=100)
    start_date = models.DateField(null=True, default=datetime.date.today())
    count_of_students = models.IntegerField(default=0)
    room = models.ForeignKey(
        "students.Room", null=True, related_name="courses",
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return f"{self.name}"


class Teacher(Person):
    course = models.ManyToManyField(to="students.Course",
                                    related_name="teachers")

    def __str__(self):
        return f"{self.email} ({self.id})"


class Room(models.Model):
    location = models.CharField(
        max_length=100,
        null=True,
        blank=True,
    )
    color = models.ForeignKey("students.Color", null=True,
                              on_delete=models.SET_NULL)


class Color(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)


class UserProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    phone = PhoneNumberField(blank=True, help_text="Contact phone number")
    birthdate = models.DateField(blank=True, null=True)
    type = models.IntegerField(blank=True, null=True)

    # 1 - Student,
    # 2 - Teacher
    # 3 -
    def __str__(self):
        return f"{self.user.first_name}_{self.user.last_name}"


class UserProfileTest(CustomUser):
    birthdate = models.DateField(blank=True, null=True)

# @receiver(post_save, sender=User)
# def update_profile_signal(sender, instance, created, **kwargs):
#     if created:
#         UserProfile.objects.create(user=instance)

students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, TextInput, EmailField
from students.models import Student, Teacher, CustomUser
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationStudentForm(UserCreationForm):
    email = EmailField(max_length=200,
                       help_text="Registration without email is not possible!")

    class Meta:
        model = CustomUser
        fields = [ 'email', 'password1', 'password2']


class PersonBaseForm(ModelForm):
    class Meta:
        model = Student
        fields = ["first_name", "last_name", "email", "phone_number", "course"]

    @staticmethod
    def normalize_name(name):
        return name.lower().strip().capitalize()

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]

        return self.normalize_name(first_name)

    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]

        return self.normalize_name(last_name)

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]
        if first_name == last_name:
            raise ValidationError("First and last names can't be equal")

        return cleaned_data


class StudentCreateForm(PersonBaseForm):
    pass


class StudentUpdateForm(PersonBaseForm):
    class Meta(PersonBaseForm.Meta):
        fields = ["first_name", "last_name", "email", "phone_number",
                  "birthdate"]


class TeacherBaseForm(PersonBaseForm):
    class Meta:
        model = Teacher
        fields = ["first_name", "last_name", "email", "phone_number", "course"]

students/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Q
from django.forms.utils import ErrorList
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.csrf import csrf_exempt
from webargs import fields

from students.forms import StudentCreateForm, TeacherBaseForm, \
    RegistrationStudentForm
from students.models import *
from students.services.emails import send_registration_email
from students.token_generator import TokenGenerator
from students.utils import format_records
from django.core.exceptions import BadRequest, ValidationError
from webargs import djangoparser
from django.contrib.auth.models import User

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, UpdateView, \
    RedirectView
from django.core.mail import send_mail, EmailMessage
from django.contrib import messages


class IndexPage(LoginRequiredMixin, TemplateView):
    template_name = "index.html"
    login_url = reverse_lazy('students:login')
    extra_context = {'name': 'Mykhailo'}
    # http_method_names = ["post"]
    # def get(self, ):
    # def dispatch(self, request, *args, **kwargs):


def hello(request):
    return HttpResponse("SUCCESS")


#
# def index(request):
#     return render(
#         request=request,
#         template_name="index.html",
#     )


parser = djangoparser.DjangoParser()


@parser.error_handler
def handle_error(error, req, schema, *, error_status_code, error_headers):
    raise BadRequest(error.messages)


@parser.use_args(
    {
        "first_name": fields.Str(
            required=False,
        ),
        "text": fields.Str(required=False),
    },
    location="query",
)
def get_students(request, params):
    students = Student.objects.all().order_by("-id")

    text_fields = ["first_name", "last_name", "email"]

    for param_name, param_value in params.items():
        if param_value:
            if param_name == "text":
                or_filter = Q()
                for field in text_fields:
                    or_filter |= Q(**{f"{field}__contains": param_value})
                students = students.filter(or_filter)
            else:
                students = students.filter(**{param_name: param_value})

    return render(
        request=request,
        template_name="students_table.html",
        context={"students_list": students},
    )


class CreateStudent(CreateView):
    # form_class = StudentCreateForm
    template_name = "students_create.html"
    fields = "__all__"
    model = Student
    initial = {
        "first_name": "default",
        "last_name": "default",
    }
    success_url = reverse_lazy("students:list")

    #
    # def get_success_url(self):
    #     return reverse("students:list")
    def form_valid(self, form):
        self.object = form.save(commit=False)
        first_name = form.cleaned_data["first_name"]
        last_name = form.cleaned_data["last_name"]
        if first_name == last_name:
            form._errors["first_name"] = ErrorList(["dsadas"])
            form._errors["last_name"] = ErrorList(
                [u"You already have an email with that name man."])
            return super().form_invalid(form)
        return super().form_valid(form)


# def create_student(request):
#     print(request.session.get("last_search_text"))
#     if request.method == "POST":
#         form = StudentCreateForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse("students:list"))
#
#     elif request.method == "GET":
#         form = StudentCreateForm()
#
#     return render(
#         request=request, template_name="students_create.html",
#         context={"form": form}
#     )


@csrf_exempt
def create_teacher(request):
    if request.method == "POST":
        form = TeacherBaseForm(request.POST)
        if form.is_valid():
            form.save()
            # return render(
            #     request=request, template_name="teacher_create.html",
            #     context={"form": form}
            # )
            return HttpResponseRedirect(reverse("students:list"))

    elif request.method == "GET":
        form = TeacherBaseForm()

    # messages.error()
    # messages.info()
    # messages.debug()
    # messages.warning()
    messages.error(request, "Teacher is successfully created.")

    return render(
        request=request, template_name="teacher_create.html",
        context={"form": form}
    )


def delete_student(request, pk):
    student = get_object_or_404(Student, id=pk)
    student.delete()

    return HttpResponseRedirect(reverse("students:list"))


class UpdateStudent(UpdateView):
    model = Student
    template_name = "students_update.html"
    fields = "__all__"
    success_url = reverse_lazy("students:list")


@csrf_exempt
def update_student(request, pk):
    student = get_object_or_404(Student, id=pk)

    if request.method == "POST":
        form = StudentCreateForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:list"))

    elif request.method == "GET":
        form = StudentCreateForm(instance=student)

    form_html = f"""
    <form method="POST">
      {form.as_p()}
      <input type="submit" value="Save">
    </form>
    """

    return HttpResponse(form_html)


def test_view(request):
    return HttpResponse(ExtendedUser.people.get_staff_users())


def search_view(request):
    search_text = request.GET.get('search')
    text_fields = ["first_name", "last_name", "email"]
    request.session["last_search_text"] = search_text
    print(request.GET)

    if search_text:
        or_filter = Q()
        for field in text_fields:
            or_filter |= Q(**{f"{field}__icontains": search_text})
        students = Student.objects.filter(or_filter)
    else:
        students = Student.objects.all().order_by("-id")

    return render(
        request=request,
        template_name="students_table.html",
        context={"students_list": students},
    )


class LoginStudent(LoginView):
    pass


class LogoutStudent(LogoutView):
    template_name = 'registration/student_logged_out.html'


class RegistrationStudent(CreateView):
    form_class = RegistrationStudentForm
    template_name = "registration/registration.html"
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        send_registration_email(request=self.request,
                                user_instance=self.object)
        return super().form_valid(form)


class ActivateUser(RedirectView):
    url = reverse_lazy('students:create-teacher')

    def get(self, request, uidb64, token, *args, **kwargs):
        print(f"uidb64: {uidb64}")
        print(f"token: {token}")

        try:
            user_pk = force_bytes(urlsafe_base64_decode(uidb64))
            print(f"user_pk: {user_pk}")
            current_user = User.objects.get(pk=user_pk)
        except (User.DoesNotExist, ValueError, TypeError):
            return HttpResponse("Wrong data")

        if current_user and TokenGenerator().check_token(current_user, token):
            current_user.is_active = True
            current_user.save()

            login(request, current_user)
            return super().get(request, *args, **kwargs)
        return HttpResponse("Wrong data")


def send_email(request):
    email = EmailMessage(subject='Registration from LMS',
                         body="Test text",
                         to=['alexfoxalt@gmail.com'])
    email.send()
    return HttpResponse('Done')

# 1. Proxy
# 2. User profile
# 3. AbstractUser
# 4. BaseAbstractUser

students/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Fixed top navbar example · Bootstrap v5.1</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">

    <link rel="canonical"
          href="https://getbootstrap.com/docs/5.1/examples/navbar-fixed/">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "index" %}">{{ name }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url "students:list" %}">All students table</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "students:create" %}">Create
                        student</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url "students:create-teacher" %}">Create
                        teacher</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url "students:registration" %}">
                        Registration</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url "social:begin" 'facebook' %}">Facebook
                        login</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url "students:logout" %}"> Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url "students:login" %}"> Login</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" method="get"
                  action="{% url "students:search" %}">
                <input class="form-control me-2" type="search"
                       name="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search
                </button>
            </form>
        </div>
    </div>
</nav>
<main class="container">
    <div class="bg-light p-5 rounded">
        {% block content %}
            <h1>Navbar example</h1>
            <p class="lead">This example is a quick exercise to illustrate how
                fixed to top navbar works. As you scroll, it will remain fixed
                to
                the top of your browser’s viewport.</p>
            <a class="btn btn-lg btn-primary" href="../components/navbar/"
               role="button">View navbar docs &raquo;</a>
        {% endblock %}
    </div>
</main>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">
</script>

</body>
</html>

students/templates/students_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <input class="btn btn-success" type="submit" value="Create"/>
        </form>
    </div>
{% endblock %}

students/templates/students_table.html
{% extends "index.html" %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone number</th>
            <th scope="col">Birthdate</th>
            <th scope="col">Age</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students_list %}
            <tr>
                <th scope="row">{{ student.id }}</th>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.phone_number }}</td>
                <td>{{ student.birthdate }}</td>
                <td>{{ student.age }}</td>
                <td>
                    <a type="button" class="btn btn-danger" href="{% url "students:delete" pk=student.id %}">Delete
                    </a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

students/templates/students_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <input class="btn btn-success" type="submit" value="Update"/>
        </form>
    </div>
{% endblock %}

students/templates/teacher_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message|safe }}
                    <a href="#" class="close">✖</a>
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <div>
        <form method="post">
            {#            {{ csrf }}#}
            {{ form|crispy }}
            <br>
            <input class="btn btn-success" type="submit" value="Create"/>
        </form>
    </div>
{% endblock %}